### ISSUE TITLE
Can't build rtaudio_test

### ISSUE THREAD

**Issue by jamshark70** [AndrewBelt/rtaudio_test#3]
Ubuntu Studio 16.04
Rack 0.5.1 (ZIP file downloaded from the main site)

1. `cd ~/share/Rack` (where I extracted the zip).
2. `git clone https://github.com/AndrewBelt/rtaudio_test.git` (per instructions, cloning the repository into the rack directory).
3. `cd rtaudio_test`
4. `make`

```
Makefile:2: ../arch.mk: No such file or directory
Makefile:27: ../compile.mk: No such file or directory
make: *** No rule to make target '../compile.mk'.  Stop.
```

(After Rack couldn't find my JACK server, I saw a reference to this utility in the FAQ and thought it would be worth a try.)

**Comment by AndrewBelt** [comment]
You need to clone it in the Rack *source* directory.

**Comment by jamshark70** [comment]
SMH. OK. Another day.
